{
    'name': 'DGN Configuration',
    'version': '0.0.1',
    'Category': 'Sales',
    'sequence': 20,
    'summary': 'Use for DGN Project',
    'author': 'HCS Viet Nam',
    'description': 'Contract Management System',
    'depends': ['base_vat', 'sale', 'stock', 'helpdesk', 'website_contract'],
    'data': [
        'security/dgn_security.xml',
        'security/ir.model.access.csv',
        'views/account_master.xml',
        'data/mail_template.xml',
        'views/dgn_helpdesk_view.xml',
        'data/dgn_cron.xml',
        'views/res_partner_view.xml',
        'views/sale_view.xml',
        'views/subscription_view.xml',
        'views/product_view.xml',
        'views/templates.xml',
        'views/login.xml',
        'wizard/payment_state_view.xml',
        'views/account_payment_view.xml',
    ],
    'qweb': [
        "static/src/xml/*.xml",
    ],
    'demo': [],
    'installable': True,
    'application': True,
}